FROM node:20-alpine AS deps
WORKDIR /app

RUN corepack enable
COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn .yarn
RUN corepack prepare yarn@4.8.1 --activate \
  && yarn install --immutable

FROM node:20-alpine AS build
WORKDIR /app

RUN corepack enable
RUN corepack prepare yarn@4.8.1 --activate

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN yarn build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./package.json
COPY --from=deps /app/node_modules ./node_modules

EXPOSE 3000
CMD ["node", "dist/main.js"]
